### ISSUE TITLE
Error moving folder into project root

### ISSUE THREAD

**Issue by jcrites** [newren/git-filter-repo#125]
Hello

Issue #32 proposed a solution for moving a directory into the project root. However, when I try to employ that solution I experience an error and a crash:

```
% ~/git-filter-repo/git-filter-repo --path lib/react-app/src --path-rename lib/react-app/src:
fatal: Empty path component found in input
fast-import: dumping crash report to .git/fast_import_crash_3427
Traceback (most recent call last):
  File "/home/jcrites/git-filter-repo/git-filter-repo", line 3913, in <module>
    filter.run()
  File "/home/jcrites/git-filter-repo/git-filter-repo", line 3850, in run
    self._parser.run(self._input, self._output)
  File "/home/jcrites/git-filter-repo/git-filter-repo", line 1414, in run
    self._parse_commit()
  File "/home/jcrites/git-filter-repo/git-filter-repo", line 1267, in _parse_commit
    self._commit_callback(commit, aux_info)
  File "/home/jcrites/git-filter-repo/git-filter-repo", line 3406, in _tweak_commit
    self._insert_into_stream(commit)
  File "/home/jcrites/git-filter-repo/git-filter-repo", line 3825, in _insert_into_stream
    self._parser.insert(obj)
  File "/home/jcrites/git-filter-repo/git-filter-repo", line 1392, in insert
    obj.dump(self._output)
  File "/home/jcrites/git-filter-repo/git-filter-repo", line 720, in dump
    change.dump(file_)
  File "/home/jcrites/git-filter-repo/git-filter-repo", line 621, in dump
    file_.write(b'M %s %s %s\n' % (self.mode, self.blob_id, quoted_filename))
BrokenPipeError: [Errno 32] Broken pipe
```

Is this use-case supported or am I unintentionally running an old version? I'll try downloading the latest release to see if there is different behavior.

```
 % ~/git-filter-repo/git-filter-repo --version
81cc263d7659
```

**Comment by jcrites** [comment]
Still experiencing this with what seems to be the latest release.

Breaking out a folder from an existing repository into the root of a new repository would probably be a common use-case, so hopefully there's a way to support it!

```
 % ~/git-filter-repo-2.27.1/git-filter-repo --path lib/react-app/src --path-rename lib/react-app/src:
fatal: Empty path component found in input
fast-import: dumping crash report to .git/fast_import_crash_4150
Traceback (most recent call last):
  File "/home/jcrites/git-filter-repo-2.27.1/git-filter-repo", line 3933, in <module>
    filter.run()
  File "/home/jcrites/git-filter-repo-2.27.1/git-filter-repo", line 3869, in run
    self._parser.run(self._input, self._output)
  File "/home/jcrites/git-filter-repo-2.27.1/git-filter-repo", line 1414, in run
    self._parse_commit()
  File "/home/jcrites/git-filter-repo-2.27.1/git-filter-repo", line 1267, in _parse_commit
    self._commit_callback(commit, aux_info)
  File "/home/jcrites/git-filter-repo-2.27.1/git-filter-repo", line 3425, in _tweak_commit
    self._insert_into_stream(commit)
  File "/home/jcrites/git-filter-repo-2.27.1/git-filter-repo", line 3844, in _insert_into_stream
    self._parser.insert(obj)
  File "/home/jcrites/git-filter-repo-2.27.1/git-filter-repo", line 1392, in insert
    obj.dump(self._output)
  File "/home/jcrites/git-filter-repo-2.27.1/git-filter-repo", line 720, in dump
    change.dump(file_)
  File "/home/jcrites/git-filter-repo-2.27.1/git-filter-repo", line 621, in dump
    file_.write(b'M %s %s %s\n' % (self.mode, self.blob_id, quoted_filename))
BrokenPipeError: [Errno 32] Broken pipe
```

```
% ~/git-filter-repo-2.27.1/git-filter-repo --version
bf25ea7ac6dc
```

**Comment by newren** [comment]
The only explanation I can think of for this is that some branch or tag or other ref had in its history either a normal file or a submodule named `lib/react-app/src`.  What's the output of
```
git log --oneline --name-status | grep -5 lib/react-app/src$
```
?

If this is indeed the problem, then using a trailing slash will fix it by not selecting the file or submodule and not attempting to rename either of those, thus:
```
git filter-repo --path lib/react-app/src/ --path-rename lib/react-app/src/:
```

However, the desire to only take files from a certain subdirectory and turn it into the new root is a common enough construct that there's a special flag just for it:
```
git filter-repo --subdirectory-filter lib/react-app/src
```
which is equivalent to the above command with the trailing slashes.

**Comment by newren** [comment]
No response; I'll assume my suggestions above fixed the problem for you, let me know if that's not the case.

**Comment by chrisseaton** [comment]
I also have this issue. I can respond to help debug it for my case.

I have a directory `IdealGraphVisualizer` which is the only directory in my repo, so I want to move all the contents of `IdealGraphVisualizer` into the root of the repository.

```
% git filter-repo --version                                  
ac039ecc095d
% git --version
git version 2.26.2
% git filter-repo --force --path-rename IdealGraphVisualizer:  
fatal: Empty path component found in input
fast-import: dumping crash report to .git/fast_import_crash_27263
Traceback (most recent call last):
  File "/usr/local/bin/git-filter-repo", line 3947, in <module>
    filter.run()
  File "/usr/local/bin/git-filter-repo", line 3883, in run
    self._parser.run(self._input, self._output)
  File "/usr/local/bin/git-filter-repo", line 1406, in run
    self._parse_commit()
  File "/usr/local/bin/git-filter-repo", line 1259, in _parse_commit
    self._commit_callback(commit, aux_info)
  File "/usr/local/bin/git-filter-repo", line 3437, in _tweak_commit
    self._insert_into_stream(commit)
  File "/usr/local/bin/git-filter-repo", line 3858, in _insert_into_stream
    self._parser.insert(obj)
  File "/usr/local/bin/git-filter-repo", line 1384, in insert
    obj.dump(self._output)
  File "/usr/local/bin/git-filter-repo", line 721, in dump
    change.dump(file_)
  File "/usr/local/bin/git-filter-repo", line 622, in dump
    file_.write(b'M %s %s %s\n' % (self.mode, self.blob_id, quoted_filename))
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by chrisseaton** [comment]
My repo is available at https://github.com/chrisseaton/igv

**Comment by rpdelaney** [comment]
I also experienced this when trying to move directories to the project root.

```console
$ git --version && git-filter-repo --version
git version 2.28.0
ac039ecc095d
```

From a UX point of view, I suspect there would be a better way to handle this case than throwing an unhandled `BrokenPipeError`. 

The `--subdirectory-filter` did what I wanted. Thank you for this tool!

**Comment by orbeckst** [comment]
I also had the error *BrokenPipeError: [Errno 32] Broken pipe* with my attempt to move the contents of a directory (Assignments/ in the example below) to the base directory
```
git filter-repo --path Assignments/ --path-rename Assignments:
``` 
but using the advice in https://github.com/newren/git-filter-repo/issues/125#issuecomment-654605619 to **append a forward slash to the directory name in the --path-rename argument**
```
git filter-repo --path Assignments/ --path-rename Assignments/:
``` 
solved the issue.
