### ISSUE TITLE
When replacing text: TypeError: %d format: a number is required, not bytes

### ISSUE THREAD

**Issue by nh2** [newren/git-filter-repo#131]
When I run `git-filter-repo --replace-text ../myexpressions.txt --refs f90c998857f59f1d52dc351aa33240cfb0a1943b..mybranch` to replace some text in my current commits, I get a crash:

```
Traceback (most recent call last):
  File "/home/niklas/src/git-filter-repo/git-filter-repo", line 3945, in <module>
    filter.run()
  File "/home/niklas/src/git-filter-repo/git-filter-repo", line 3881, in run
    self._parser.run(self._input, self._output)
  File "/home/niklas/src/git-filter-repo/git-filter-repo", line 1406, in run
    self._parse_commit()
  File "/home/niklas/src/git-filter-repo/git-filter-repo", line 1259, in _parse_commit
    self._commit_callback(commit, aux_info)
  File "/home/niklas/src/git-filter-repo/git-filter-repo", line 3434, in _tweak_commit
    aux_info['had_file_changes'], orig_parents):
  File "/home/niklas/src/git-filter-repo/git-filter-repo", line 3195, in _prunable
    self._output.write(b"ls :%d %s\n" % (parent, quoted_filename))
TypeError: %d format: a number is required, not bytes
fatal: stream ends early
fast-import: dumping crash report to .git/fast_import_crash_31016
```

When I print `repr(parent)` at the crash location, it's `b'f90c998857f59f1d52dc351aa33240cfb0a1943b'`.

This is on git-filter-repo commit cefeef1c0a72aa9a928801815fbe330cc61a5774.

**Comment by newren** [comment]
Thanks for the report!  Fixed with commit d79ea709b7 (filter-repo: fix crash from assuming parent is an int, 2020-07-27).
