### ISSUE TITLE
--state-branch appears to not work at all

### ISSUE THREAD

**Issue by tarsius** [newren/git-filter-repo#141]
Note sure if I am using this right--you hide this argument well. :grin: 

```
git clone git@github.com:zenspider/elisp.git
cd elisp
git filter-repo --state-branch state --path autotest.el
Traceback (most recent call last):
  File "/home/jonas/.local/bin/git-filter-repo", line 3913, in <module>
    filter.run()
  File "/home/jonas/.local/bin/git-filter-repo", line 3850, in run
    self._parser.run(self._input, self._output)
  File "/home/jonas/.local/bin/git-filter-repo", line 1414, in run
    self._parse_commit()
  File "/home/jonas/.local/bin/git-filter-repo", line 1267, in _parse_commit
    self._commit_callback(commit, aux_info)
  File "/home/jonas/.local/bin/git-filter-repo", line 3413, in _tweak_commit
    self._insert_into_stream(alias)
  File "/home/jonas/.local/bin/git-filter-repo", line 3825, in _insert_into_stream
    self._parser.insert(obj)
  File "/home/jonas/.local/bin/git-filter-repo", line 1392, in insert
    obj.dump(self._output)
  File "/home/jonas/.local/bin/git-filter-repo", line 887, in dump
    file_.write(b'alias\nmark :%d\nto :%d\n\n' % (self.ref, self.to_ref))
TypeError: %d format: a number is required, not bytes
fatal: stream ends early
fast-import: dumping crash report to .git/fast_import_crash_10510
```

**Comment by newren** [comment]
Ugh, another case of always using marks when hashes might be present.  Whoops.  There's several places this has been fixed up in the code (search for isinstance.*int); based on whether ref or to_ref are ints or bytestrings representing hashes, they should be written with the ':%d' or '%s' specifiers.

Might be an easy fix for someone else wanting to contribute.  If not, I'll loop back and fix it up later.

**Comment by tarsius** [comment]
Thanks for the information! (I am not gonna try to fix this myself soon, but at least I have a lead for when I work on related things again.)

**Comment by tarsius** [comment]
I have tried doing what you suggested but I either made a mistake or there is more to it in this case:

```diff
diff --git a/git-filter-repo b/git-filter-repo
index 22826b5..df90679 100755
--- a/git-filter-repo
+++ b/git-filter-repo
@@ -885,7 +885,16 @@ class Alias(_GitElement):
     """
     self.dumped = 1
 
-    file_.write(b'alias\nmark :%d\nto :%d\n\n' % (self.ref, self.to_ref))
+    file_.write(b'alias\n')
+    if isinstance(self.ref, int):
+      file_.write(b'mark :%d\n' % self.ref)
+    else:
+      file_.write(b'mark %s\n' % self.ref)
+    if isinstance(self.to_ref, int):
+      file_.write(b'to :%d\n' % self.to_ref)
+    else:
+      file_.write(b'to %s\n' % self.to_ref)
+    file_.write(b'\n')
 
 class FastExportParser(object):
   """
```

results in

```
git: builtin/fast-import.c:3232: parse_alias: Assertion `e' failed.
Traceback (most recent call last):
  File "/home/jonas/bin/git-filter-repo", line 4013, in <module>
    main()
  File "/home/jonas/bin/git-filter-repo", line 4010, in main
    filter.run()
  File "/home/jonas/bin/git-filter-repo", line 3945, in run
    self._parser.run(self._input, self._output)
  File "/home/jonas/bin/git-filter-repo", line 1418, in run
    self._parse_commit()
  File "/home/jonas/bin/git-filter-repo", line 1269, in _parse_commit
    self._commit_callback(commit, aux_info)
  File "/home/jonas/bin/git-filter-repo", line 3501, in _tweak_commit
    self._insert_into_stream(alias)
  File "/home/jonas/bin/git-filter-repo", line 3920, in _insert_into_stream
    self._parser.insert(obj)
  File "/home/jonas/bin/git-filter-repo", line 1396, in insert
    obj.dump(self._output)
  File "/home/jonas/bin/git-filter-repo", line 896, in dump
    file_.write(b'to %s\n' % self.to_ref)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by kasperlewau** [comment]
@tarsius Did you end up finding a solution to the BrokenPipeError? 
I'm seeing the very same on my end, with similar changes to yours. 
I noticed as soon as I drop the `--paths`, or `--paths-from-file` flag from my invocation the stream doesn't yield a BrokenPipeError.

**Comment by tarsius** [comment]
> Did you end up finding a solution to the BrokenPipeError?

Unfortunately not.

**Comment by kasperlewau** [comment]
The way I've gotten around the issue(s) with `--state-branch` are twofold: 
1. Specify absolute paths to `--target`, `--source` & `--paths-from-file`. 
2. Pass `--prune-empty never`.

It's working fine right now. I'll report back should I hit any other snags. 

For reference, this is the full command I'm issuing 

```
git-filter-repo \
  --debug \
  --source /repositories/src \
  --target /repositories/dst1 \
  --paths-from-file /repositories/dst1-include \
  --refs main release \
  --prune-empty never \
  --state-branch _state
  ```
