### ISSUE TITLE
TypeError: %b requires a bytes-like object, or an object that implements __bytes__, not 'str'

### ISSUE THREAD

**Issue by mjamro** [newren/git-filter-repo#183]
When i run the script using following command:

```
 python ../git-filter-repo.py --commit-callback '
    commit.author_name = "foo"
    commit.author_email = "foo@foo.bar"
  '
```

i get TypeError:

```
Traceback (most recent call last):
  File "../git-filter-repo.py", line 3950, in <module>
    filter.run()
  File "../git-filter-repo.py", line 3886, in run
    self._parser.run(self._input, self._output)
  File "../git-filter-repo.py", line 1409, in run
    self._parse_commit()
  File "../git-filter-repo.py", line 1260, in _parse_commit
    self._commit_callback(commit, aux_info)
  File "../git-filter-repo.py", line 3440, in _tweak_commit
    self._insert_into_stream(commit)
  File "../git-filter-repo.py", line 3861, in _insert_into_stream
    self._parser.insert(obj)
  File "../git-filter-repo.py", line 1387, in insert
    obj.dump(self._output)
  File "../git-filter-repo.py", line 701, in dump
    file_.write((b'commit %s\n'
TypeError: %b requires a bytes-like object, or an object that implements __bytes__, not 'str'
fatal: stream ends early
fast-import: dumping crash report to .git/fast_import_crash_2636
```

My env is:

- Python 3.8.5
- git version 2.28.0.windows.1

which seems fine with the requirements for git-filter-repo (git >= 2.24.0 and python > 3.5). Can you please provide some help on what's wrong?

**Comment by newren** [comment]
Try changing to the following:
```
 python ../git-filter-repo.py --commit-callback '
    commit.author_name = b"foo"
    commit.author_email = b"foo@foo.bar"
  '
```

Note the use of bytestrings, b"..." instead of just "...".  See https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#CALLBACKS from the manual, in particular the part that reads

    One important thing to note for all callbacks is that filter-repo uses bytestrings (see 
    https://docs.python.org/3/library/stdtypes.html#bytes) everywhere instead of strings.

That should fix your problem here.
