### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by schabluk** [newren/git-filter-repo#27]
Hi,

I'm getting error with `bfg-ish` script on Windows, Python version is 3.7.1.

```
Traceback (most recent call last):
  File "./bfg-ish", line 437, in <module>
    bfg.run()
  File "./bfg-ish", line 370, in run
    preserve_refs = self.get_preservation_info(bfg_args.preserve_ref_tips)
  File "./bfg-ish", line 314, in get_preservation_info
    output = subprocess.check_output(['git', 'rev-parse'] + ref_trees)
  File "C:\Tools\Anaconda\lib\subprocess.py", line 389, in check_output
    **kwargs).stdout
  File "C:\Tools\Anaconda\lib\subprocess.py", line 466, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Tools\Anaconda\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "C:\Tools\Anaconda\lib\subprocess.py", line 1113, in _execute_child
    args = list2cmdline(args)
  File "C:\Tools\Anaconda\lib\subprocess.py", line 524, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'
```

This is the line 314:
```python
output = subprocess.check_output(['git', 'rev-parse'] + ref_trees)
```
It works when I decode byte-string to string:
```python
output = subprocess.check_output(['git', 'rev-parse'] + [r.decode("utf-8") for r in ref_trees])
```
But then it fails in other places:

```
Traceback (most recent call last):
  File "./git-cleaner", line 438, in <module>
    bfg.run()
  File "./git-cleaner", line 425, in run
    self.revert_tree_changes(preserve_refs)
  File "./git-cleaner", line 329, in revert_tree_changes
    output = subprocess.check_output('git cat-file -p'.split()+[ref])
  File "C:\Tools\Anaconda\lib\subprocess.py", line 389, in check_output
    **kwargs).stdout
  File "C:\Tools\Anaconda\lib\subprocess.py", line 466, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Tools\Anaconda\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "C:\Tools\Anaconda\lib\subprocess.py", line 1113, in _execute_child
    args = list2cmdline(args)
  File "C:\Tools\Anaconda\lib\subprocess.py", line 524, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'
```

**Comment by newren** [comment]
Ah, indeed, a repeat of issue 6 but this time for the bfg-ish script.  I should convert all its uses of subprocess to re-use the SubprocessWrapper created to fix that issue.  There's probably a couple in filter-lamely that should be fixed up too.  Thanks for the report; I'll try to fix it up in the next few days.

**Comment by newren** [comment]
Okay, apparently I took a lot longer than "the next few days" to get back to this.  But I finally did.

I updated both the bfg-ish and filter-lamely scripts to use the SubprocessWrapper that fixed the same issue for git-filter-repo on windows, so it should be good now.  Thanks for the report!
