### ISSUE TITLE
Usage of --state-branch, incremental buildup of filtered repositories

### ISSUE THREAD

**Issue by kasperlewau** [newren/git-filter-repo#302]
Hi, 
I'm looking into leveraging the `--state-branch` flag to continuously filter from a source repository, by ref(s), to several subsets of that source repositories. So far it's not going so great, some modifications on my end may be needed. 

I had an initial attempt at turning --state-branch on like so: 
```
git-filter-repo \
  --source src-repo \
  --target dst-repo \
  --paths-from-file tiny.txt \
  --refs main \
  --state-branch main
  
fatal: could not open 'dst-repo/.git/filter-repo/source-marks' for reading: No such file or directory

Error: fast-export failed; see above.
fatal: cannot read 'dst-repo/.git/filter-repo/target-marks': No such file or directory
fast-import: dumping crash report to .git/fast_import_crash_1796
```

Where `src-repo` has some history, and `dst-repo` is a fresh git dir. 
`dst-repo/.git/filter-repo/{source,target}-marks` files have been written at this point, but they're empty. A second run of the same arguments produce the same result. 

--- 

On my second go, I went for a `--dry-run` and a copy of the fast-export.original|filtered files to the expected path in the target repository ref (`git -C dst-repo show refs/heads/main:source-marks` and `target-marks`, respectively). 

```
git-filter-repo \
  --source src-repo \
  --target dst-repo \
  --paths-from-file tiny.txt \
  --refs main \
  --dry-run

Parsed 1000 commits
New history written in 2.19 seconds...
NOTE: Not running fast-import or cleaning up; --dry-run passed.
      Requested filtering can be seen by comparing:
        dst-repo/.git/filter-repo/fast-export.original
        dst-repo/.git/filter-repo/fast-export.filtered

cp dst-repo/.git/filter-repo/fast-export.original dst-repo/source-marks
cp dst-repo/.git/filter-repo/fast-export.filtered dst-repo/target-marks
git -C dst-repo checkout -b main
Switched to a new branch 'main'
git -C dst-repo add source-marks target-marks
git -C dst-repo commit -m "New marks"
[main (root-commit) 9ba01c4] New marks
 2 files changed, 8811408 insertions(+)
 create mode 100644 source-marks
 create mode 100644 target-marks

git-filter-repo \
  --source src-repo \
  --target dst-repo \
  --paths-from-file tiny.txt \
  --refs main \
  --state-branch main
  
Aborting: Refusing to destructively overwrite repo history since
this does not look like a fresh clone.
  (refs/heads/main exists, but refs/remotes/origin/main not found)
Please operate on a fresh clone instead.  If you want to proceed
anyway, use --force.

# Applying force 
git-filter-repo \
  --source src-repo \
  --target dst-repo \
  --paths-from-file tiny.txt \
  --refs main \
  --state-branch main \
  --force 
  
Traceback (most recent call last):
  File "/usr/local/bin/git-filter-repo", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/git_filter_repo.py", line 4001, in main
    filter.run()
  File "/usr/local/lib/python3.8/dist-packages/git_filter_repo.py", line 3924, in run
    self._setup_input(use_done_feature = True)
  File "/usr/local/lib/python3.8/dist-packages/git_filter_repo.py", line 3658, in _setup_input
    source_marks_file = self._load_marks_file(b'source-marks')
  File "/usr/local/lib/python3.8/dist-packages/git_filter_repo.py", line 3577, in _load_marks_file
    biggest_id = max(int(x.split()[0][1:]) for x in contents.splitlines())
  File "/usr/local/lib/python3.8/dist-packages/git_filter_repo.py", line 3577, in <genexpr>
    biggest_id = max(int(x.split()[0][1:]) for x in contents.splitlines())
ValueError: invalid literal for int() with base 10: b'eature'
```

So not a whole lot better. My guess is, the .original/.filtered dry-run(or, debug files) aren't 1:1 with the expected format of `_load_marks_file`. 

--- 

Third time at it, I went for changing the `--import-marks` flags to `--import-marks-if-exist`. That _feels_ more correct to me, for the first round of filtering anyway.

```
sed -i 's/import-marks/import-marks-if-exists/g' /usr/local/lib/python3.8/dist-packages/git_filter_repo.py
git-filter-repo \
  --source src-repo \
  --target dst-repo \
  --paths-from-file tiny.txt \
  --refs main \
  --state-branch main
  
Parsed 974 commitsfatal: Unable to open marks file dst-repo/.git/filter-repo/source-marks for writing.: No such file or directory
Parsed 1000 commits
Error: fast-export failed; see above.
fatal: stream ends early
fast-import: dumping crash report to .git/fast_import_crash_1892
```

I wouldn't expect for there to be a marks file of what to import/export, given a prior run hasn't happened. I believe in the git_filter_repo code, writing of marks to disk is enabled through the `--state-branch` flag. But, the flag comes at the cost of requiring the files on disk prior (and, in an acceptable format as far as I can tell). 

---

At this point I'm not sure how to attack the problem further.

**Comment by kasperlewau** [comment]
Closing. Passing absolute paths to git-filter-repo made the internal path resolution(s) work just fine. 
```
git-filter-repo --source /repositories/src --target /repositories/dst --state-branch _filterstate
```
Unfortunately it doesn't seem to work in tandem with `--paths-from-file`, see https://github.com/newren/git-filter-repo/issues/141#issuecomment-970748926
