### ISSUE TITLE
TypeError: CreateProcess() argument 8 must be str or None, not bytes

### ISSUE THREAD

**Issue by justdan96** [newren/git-filter-repo#6]
On Windows I am seeing the following error:

`git filter-repo --mailmap dan-mailmap.txt

Traceback (most recent call last):

  File "git-filter-repo", line 3437, in <module>

  File "git-filter-repo", line 3335, in run

  File "git-filter-repo", line 2904, in _run_sanity_checks

  File "git-filter-repo", line 3154, in results_tmp_dir

  File "git-filter-repo", line 1870, in determine_git_dir

  File "subprocess.py", line 395, in check_output

  File "subprocess.py", line 472, in run

  File "subprocess.py", line 775, in __init__

  File "subprocess.py", line 1178, in _execute_child

TypeError: CreateProcess() argument 8 must be str or None, not bytes

[66484] Failed to execute script git-filter-repo`

This is using the latest version of the repo. I've altered the script to force it to use the subprocess wrapper and even forced it not to use the wrapper and changed all "cwd=" statements to use decode and still I am seeing an error. I am using Python 3.7.

**Comment by newren** [comment]
Thanks for the report!  I suspected something like this and asked in issue #4 but never got an answer.  Could you run the following and report if you get the same error:

`subprocess.check_output(["git",` b"--version"])`

If so, I can extend the wrappers to not only unicode-ify the cwd argument, but also the args list.

**Comment by justdan96** [comment]
I'll try that out at work tomorrow. I assume I can do that just in a
vanilla Python prompt?

**Comment by newren** [comment]
Yes, you should be able to try that out at a vanilla python prompt, though you'll need to first run `import subprocess` within the python prompt to make sure it has the 'subprocess' module loaded.

**Comment by newren** [comment]
Have you had a chance to take a look?

**Comment by justdan96** [comment]
```
>>> import subprocess

>>> subprocess.check_output(["git", b"--version"])

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "E:\python37\lib\subprocess.py", line 395, in check_output

    **kwargs).stdout

  File "E:\python37\lib\subprocess.py", line 472, in run

    with Popen(*popenargs, **kwargs) as process:

  File "E:\python37\lib\subprocess.py", line 775, in __init__

    restore_signals, start_new_session)

  File "E:\python37\lib\subprocess.py", line 1119, in _execute_child

    args = list2cmdline(args)

  File "E:\python37\lib\subprocess.py", line 530, in list2cmdline

    needquote = (" " in arg) or ("\t" in arg) or not arg

TypeError: a bytes-like object is required, not 'str'
```

**Comment by newren** [comment]
Wow, kinda lame that this isn't an intrinsic windows issue, but Python itself just assumes everything is a (unicode) string.  Anyway, I think my workaround in the windows-workarounds branch should fix this.  Could you give it a try?

**Comment by justdan96** [comment]
I'll give it a try tomorrow, will let you know

**Comment by newren** [comment]
Cool, thanks for testing it out.  I've merged the change into the master branch.  As far as push restrictions, yeah if you have some kind of aggressive hooks on the server that only let you push your own commits up, then that wouldn't work well with filter-repo since it edits all the commits in the repo creating new ones (and then deletes the old ones).  If this is gerrit you are using, https://gerrit-review.googlesource.com/Documentation/access-control.html#category_forge_author (and forge committer right after it) may help, but it's going to be entirely dependent on the git server you're using.

Thanks for the heads up on PyInstaller; I may look into it at some point.  Or I may delay until someone else does it for me.  :-)
