### ISSUE TITLE
`assert(usoa == intermediate)` could fail in subsequent filter-repo runs

### ISSUE THREAD

**Issue by louiswpf** [newren/git-filter-repo#618]
`assert(usoa == intermediate)` could fail in subsequent filter-repo runs.
This is caused by the metadata stored in `$GIT_DIR/filter-repo`.

Here is a reproducer:
* test.sh
```sh
#!/bin/sh -ex

git init -q repo
cd repo
touch file
git add file
git commit -q -m 'Initial commit'
orig_commit_id="$(git rev-parse HEAD)"
git filter-repo --quiet --to-subdirectory-filter dir0 --force --partial
git reset -q "${orig_commit_id}"
git filter-repo --quiet --to-subdirectory-filter dir1
git filter-repo --quiet --to-subdirectory-filter dir1

```

```sh
$ ./test.sh
+ git init -q repo
+ cd repo
+ touch file
+ git add file
+ git commit -q -m 'Initial commit'
++ git rev-parse HEAD
+ orig_commit_id=3bf1e5885e1dba5a890a91e1e3a3036c9f7fa867
+ git filter-repo --quiet --to-subdirectory-filter dir0 --force --partial
New history written in 0.01 seconds...
Completely finished after 0.02 seconds.
+ git reset -q 3bf1e5885e1dba5a890a91e1e3a3036c9f7fa867
+ git filter-repo --quiet --to-subdirectory-filter dir1
New history written in 0.01 seconds; now repacking/cleaning...
Completely finished after 0.04 seconds.
+ git filter-repo --quiet --to-subdirectory-filter dir1
New history written in 0.01 seconds; now repacking/cleaning...
Traceback (most recent call last):
  File "/usr/bin/git-filter-repo", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/git_filter_repo.py", line 4973, in main
    filter.run()
  File "/usr/lib/python3.12/site-packages/git_filter_repo.py", line 4936, in run
    self._record_metadata(self.results_tmp_dir(), self._orig_refs)
  File "/usr/lib/python3.12/site-packages/git_filter_repo.py", line 4767, in _record_metadata
    self._compute_metadata(metadata_dir, orig_refs)
  File "/usr/lib/python3.12/site-packages/git_filter_repo.py", line 4712, in _compute_metadata
    assert(usoa == intermediate) # old wasn't pruned => usoa == intermediate
           ^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by prithvipatil** [comment]
Seeing the same issue. It worked for few times for "--path-rename". After that, it stopped working and throwing this error. How to resolve the issue? Is there any workaround?

**Comment by obersteiner** [comment]
I can verify this issue. Is the final state still valid (even with the assertion meaning that just the check is buggy) or is the actual result of the repository in an invalid state for git?

**Comment by glensc** [comment]
Workaround: delete previous state:

```
$ find .git/filter-repo
.git/filter-repo
.git/filter-repo/changed-refs
.git/filter-repo/suboptimal-issues
.git/filter-repo/first-changed-commits
.git/filter-repo/commit-map
.git/filter-repo/already_ran
.git/filter-repo/ref-map
$ rm -rf .git/filter-repo
```

**Comment by xixixao** [comment]
Also ran into this just now

**Comment by ackerleytng** [comment]
I also ran into this, and I was trying to run filter-repo to change commit messages with `--refs aaa..bbb` where `bbb` is not `HEAD`.

(`aaa` is before `bbb` and the commits are linear (no merges, etc))
