### ISSUE TITLE
commitsfatal: Empty path component found in input when attempting to export subdirectory

### ISSUE THREAD

**Issue by joeapearson** [newren/git-filter-repo#73]
I'm trying to split off a subdirectory of a larger git repo into a separate new repository.  I've encountered a crash along the way and I suspect my source repo is corrupted in some way.

In a freshly cloned source repo I am running this command, where `path/to/subdir` is the desired root:

```sh
$ git filter-repo --path path/to/subdir --to-subdirectory-filter / --refs master
```

The output I receive is:

```
Parsed 3958 commitsfatal: Empty path component found in input
fast-import: dumping crash report to .git/fast_import_crash_53647
Traceback (most recent call last):
  File "/usr/local/bin/git-filter-repo", line 3913, in <module>
    filter.run()
  File "/usr/local/bin/git-filter-repo", line 3850, in run
    self._parser.run(self._input, self._output)
  File "/usr/local/bin/git-filter-repo", line 1414, in run
    self._parse_commit()
  File "/usr/local/bin/git-filter-repo", line 1267, in _parse_commit
    self._commit_callback(commit, aux_info)
  File "/usr/local/bin/git-filter-repo", line 3407, in _tweak_commit
    self._record_remapping(commit, orig_parents)
  File "/usr/local/bin/git-filter-repo", line 3190, in _record_remapping
    self._output.flush()
BrokenPipeError: [Errno 32] Broken pipe
~/dev/avid/sibelius-platform
```

Crash report:

```
fast-import crash report:
    fast-import process: 53647
    parent process     : 53646
    at 2020-04-13 17:08:38 +0000

fatal: Empty path component found in input

Most Recent Commands Before Crash
---------------------------------
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  from :3543
  
  reset refs/heads/master
  commit refs/heads/master
  mark :4413
  author me <e@d.com> 1527713831 -0700
  committer me <e@d.com> 1527713831 -0700
  data 30
  
  get-mark :4413
  commit refs/heads/master
  mark :4414
  author me <e@d.com> 1527713831 -0700
  committer me <e@d.com> 1527713831 -0700
  data 53
  from :4413
  merge :3543
* M 100644 c1e6e594e1523aab72e21b0c41710af8072c88a5 /path/to/subdir/.ci.yml

Active Branch LRU
-----------------
    active_branches = 1 cur, 5 max

  pos  clock name
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   1)      7 refs/heads/master

Inactive Branches
-----------------
refs/heads/master:
  status      : active loaded
  tip commit  : 7b049cfe7a8196d661b6b52bd2c0be13bb11f45e
  old tree    : 4b825dc642cb6eb9a060e54bf8d69288fbee4904
  cur tree    : 4b825dc642cb6eb9a060e54bf8d69288fbee4904
  commit clock: 7
  last pack   : 0


Marks
-----
:1 f9a2f212a981364eecf7ad29f25dd248c1f618ae
:10 f616ac0f19c1b76fcf7d126c5c71c931231ac9f3
:11 dfe022c9ea35837f3302d1d285a84c6fea1d27e6
:28 ef34d526a821ffa538448b3bf90ae36351db480d
:30 c8b3ca231ca78fd0e6b2ee30389b053e74f2ceb5
:70 c4a0620eae92d9cf4f661b3979e8af19c2612434
:132 539a82aa1490491bb60678af4be0f7dc9f468306
:195 d9ffe3aa132197a982cd1b87e351b5ba5fc9070c
:557 3b07809156ecb7de60064bc316b0bbb38dc15446
:645 2be8b991e6a9c1a89bd5845e574947fd2600ae9e
:646 73c6c2df8f0f0125fa67631719f6b4c623573ee4
:647 0d1e8c8bd371d3fd4b0a3af9c7a83ba48559ceb6
:777 4a36840de7f9191e5f14a4d1a1e131d85ddb101c
:1258 baef1f7fcb64d9e46b53ca9db76127278e260aa4
:1284 9a7222a8ff0e05fe0d94710fec5354c89c7fd770
:1285 518804be2c6380379556612598500ea9905c8b15
:1286 7b69128a6d8d803b3c15776e8878bc8deded97cb
:1443 e404de0e65785f5f639bb694a630e33a8d5575bd
:1480 87ce442a97ff717b9efbb48b0004848eb0101037
:1495 84d9cd7284b9b9712c405a5967ae50802ecb7845
:1515 f06d578d8fe5176af12d49d0be0f391f42d4c93f
:1628 51f1d3b8dbbb046e3b5ae5e26d3c41cbbbd758d0
:1629 f17c765c6599129671bc87dee8f1b0b99dd1f1aa
:1802 3ea1629dda2c9c0af1dd428053ff6d1adbb5b7c7
:2878 2b97f48b07eabd8c1370121a8c5da4b02a3431a3
:2879 77e33c913b3411688527fd2544da9cf5c24f25c4
:3444 a9cdbc0361e55530b94ec8fb6de626d3c888d853
:3542 f629c6a7f06419fcdca803fd11bc1594c72fb00b
:3543 0ef6c359374fbc0fc6244c4c7beea1d8631a6a0a
:4413 7b049cfe7a8196d661b6b52bd2c0be13bb11f45e

-------------------
END OF CRASH REPORT
```

Is there any workaround?

**Comment by newren** [comment]
Yeah, apparently my description of --subdirectory-filter and --to-subdirectory-filter must be pretty bad; people keep using them in ways that are totally surprising to me relative to what I intended.  Anyway, what you want is basically this:

```
$ git filter-repo --subdirectory-filter path/to/subdir --refs master
```

although I'm not sure why you had `--refs master` on your original; I'd likely leave it out.  (And yes, note that I used --subdirectory-filter, not --to-subdirectory-filter.)

I'll see if I can do something to improve the wording of these descriptions, and to throw an error message if either --subdirectory-filter or --to-subdirectory-filter are specified with a directory name that begins with a '/'.  (and perhaps more generally do that with --path-rename too)

**Comment by joeapearson** [comment]
Thanks @newren for the help and sorry for the misunderstanding, I think this is a case of RTFM!  I tried what you suggested and it worked perfectly.

Clearer error messages would have helped guide me on the right path, thanks for any improvements you make.

**Comment by zhaojiangbin** [comment]
This just happened to me, too. I am also moving a subdirectory out of a large repo into its own. Found this issue and it helped me. Perhaps this is a common use case that deserves mentioned in the EXAMPLES section?

And thank you @newren for the great tool.

**Comment by newren** [comment]
Yeah, you two aren't the first two.  I think there's been another 3 cases or so, so they're adding up.  I think I both need to clarify the wording of these options and add some specific examples.  Reopening to make sure this gets done.

**Comment by newren** [comment]
Okay, I pushed some commits that will (a) throw a simple error message if the user specifies any path starting with a slash, and (b) included two examples in the documentation, one each for --subdirectory-filter and --to-subdirectory-filter, together with simple picture of the full directory hierarchy before and after to clarify how these two are meant to work.

Thanks for the reports!
